{% raw -%}
---
- name: Assert variables
  assert:
    that: "{{ extravars }} is defined"
    msg: "{{ extravars  }} is not defined"
  loop: "{{ assert_vars | default([]) + ['env'] }}"
  loop_control:
    loop_var: extravars

- name: Set global fact for base dir
  set_fact:
    base_dir: "{{ lookup('env','PWD') }}"
    item_dir: "{{ playbook_dir | basename }}"

- name: Read all variables
  block:
    - name: Get stats on all variable files
      stat:
        path: "{{ item }}"
      with_fileglob:
        - "{{ base_dir }}/vars/{{ env }}/common.yml"
        - "{{ base_dir }}/vars/{{ env }}/secrets.vault"
      register: _variables_stat

    - name: Include all variable files (only when found)
      include_vars: "{{ item.stat.path }}"
      when: item.stat.exists
      loop: "{{ _variables_stat.results | flatten(levels=1) }}"
      loop_control:
        label: "{{ item.stat.path }}"
      no_log: true

  run_once: true
  delegate_to: localhost
  become: false

{%- endraw %}
